# Generated by Django 3.2.18 on 2023-04-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201121_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalgroupdescription',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical group description', 'verbose_name_plural': 'historical group descriptions'},
        ),
        migrations.AlterField(
            model_name='historicalgroupdescription',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
