# Generated by Django 3.1.3 on 2020-11-21 03:05

import django.core.validators
from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='body',
            field=django_bleach.models.BleachField(help_text='HTML content of the agreement. The following tags are allowed: h3, p, a, abbr, cite, code, small, em, strong, sub, sup, u, ul, ol, li, br. Changing this field after the agreement has been signed by patrons is strongly discouraged.'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='redirect_url',
            field=models.URLField(help_text="URL displayed to patrons after signing the agreement. It is prefixed by the text 'Return to '. It must start with 'https://'.", validators=[django.core.validators.URLValidator(code='need_https', message="Enter a valid URL. It must start with 'https://'.", schemes=['https'])]),
        ),
        migrations.AlterField(
            model_name='historicalagreement',
            name='body',
            field=django_bleach.models.BleachField(help_text='HTML content of the agreement. The following tags are allowed: h3, p, a, abbr, cite, code, small, em, strong, sub, sup, u, ul, ol, li, br. Changing this field after the agreement has been signed by patrons is strongly discouraged.'),
        ),
        migrations.AlterField(
            model_name='historicalagreement',
            name='redirect_url',
            field=models.URLField(help_text="URL displayed to patrons after signing the agreement. It is prefixed by the text 'Return to '. It must start with 'https://'.", validators=[django.core.validators.URLValidator(code='need_https', message="Enter a valid URL. It must start with 'https://'.", schemes=['https'])]),
        ),
        migrations.AlterField(
            model_name='historicalresource',
            name='description',
            field=django_bleach.models.BleachField(blank=True, help_text='An HTML description of the resource. The following tags are allowed: h3, p, a, abbr, cite, code, small, em, strong, sub, sup, u, ul, ol, li, br.'),
        ),
        migrations.AlterField(
            model_name='historicalresource',
            name='low_codes_email',
            field=models.CharField(blank=True, help_text='The recipient of email warnings about low numbers of remaning unassigned license codes. If empty, no emails are sent.', max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=django_bleach.models.BleachField(blank=True, help_text='An HTML description of the resource. The following tags are allowed: h3, p, a, abbr, cite, code, small, em, strong, sub, sup, u, ul, ol, li, br.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='low_codes_email',
            field=models.CharField(blank=True, help_text='The recipient of email warnings about low numbers of remaning unassigned license codes. If empty, no emails are sent.', max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
