# Generated by Django 3.2.18 on 2023-04-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20201121_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalagreement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical agreement', 'verbose_name_plural': 'historical agreements'},
        ),
        migrations.AlterModelOptions(
            name='historicaldepartment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical department', 'verbose_name_plural': 'historical departments'},
        ),
        migrations.AlterModelOptions(
            name='historicalfaculty',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical faculty', 'verbose_name_plural': 'historical facultys'},
        ),
        migrations.AlterModelOptions(
            name='historicallicensecode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical license code', 'verbose_name_plural': 'historical license codes'},
        ),
        migrations.AlterModelOptions(
            name='historicalresource',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resource', 'verbose_name_plural': 'historical resources'},
        ),
        migrations.AlterModelOptions(
            name='historicalsignature',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical signature', 'verbose_name_plural': 'historical signatures'},
        ),
        migrations.AlterField(
            model_name='historicalagreement',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfaculty',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallicensecode',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalresource',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsignature',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
